# Site settings
title : Nick Krabbenhoeft
author : Nick Krabbenhoeft
email : n@nkrabben.com
description : > # this means to ignore newlines until "baseurl:"
  Portfolio of Nick Krabbenhoeft's work, publications, skills, and education.
baseurl : "" # the subpath of your site, e.g. /blog/
url : "http://nkrabben.com" # the base hostname & protocol for your site
twitter_username : nkrabben
github_username :  nkrabben

# Build settings
markdown: kramdown
